modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "materia" #mandatory
version = "1.0" #mandatory

displayName = "Materia" #mandatory
#updateJSONURL = "http://myurl.me/" #optional
#displayURL = "http://example.com/" #optional
issueTrackerURL="https://github.com/Tavi007/Materia/issues" #optional
logoFile = "materiaLogo.png"
credits = "Thanks goes to the Forge Forum community." #optional
authors = "Tavi007" #optional

description='''
I have to do this later. lol
'''

# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.materia]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.materia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
